echo "What name would you give to your project?";
read projectName;
echo "Creating the project root folder";
mkdir $projectName;
cd $projectName;
echo "Creating images folder";
mkdir images;
echo "Creating js folder";
mkdir js;
echo "creating app.js file"
touch js/app.js;
echo "Creating css folder";
mkdir css;
echo "Creating master.css file";
touch css/master.css;
echo "Creating index.html";
touch index.html;
echo "Creating .gitignore file";
echo ".DS_Store" >> .gitignore;
echo "Intitilizing the git repository";
git init;
